Implement AccountReader for aggregate accounts
ualibweb/mod-data-export-worker pull request #73
Opened 2023-03-29 22:09 UTC by nhanaa

2023-03-29 22:11 UTC, ncovercash requested changes
Please spin the `AccountReader` you have into a separate one, maybe `AggregateAccountReader` -- we'll configure Spring Batch to use `AccountReader` for non-aggregate workflows and `AggregateAccountReader` for aggregate ones, so we need both.

2023-03-30 20:33 UTC, nhanaa commented
@ncovercash I've created and moved the stuff over to AggregatedAccountsReader

2023-04-03 20:19 UTC, ncovercash approved these changes

2023-04-03 20:19 UTC, ncovercash commented on src/main/java/org/folio/dew/batch/bursarfeesfines/AccountReader.java
> +import com.google.inject.Key;
Are all these still necessary? @nhanaa 

Clean up the imports then you should be good to merge

2023-04-03 20:24 UTC, merged